// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function EnsureAgent():Promise<void>;

export function GetSessionDetail(arg1:string):Promise<main.SessionDetail>;

export function GetStatus():Promise<main.AgentStatus>;

export function ListSessions(arg1:string,arg2:string,arg3:number):Promise<main.SessionList>;

export function Login(arg1:main.LoginRequest):Promise<main.AgentStatus>;

export function Logout():Promise<main.AgentStatus>;

export function Offline():Promise<main.AgentStatus>;

export function ReplySession(arg1:string,arg2:string):Promise<void>;

export function SaveSettings(arg1:main.AgentLocalSettings):Promise<main.AgentLocalSettings>;
