// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ContinueAIToolSession(arg1, arg2) {
  return window['go']['main']['App']['ContinueAIToolSession'](arg1, arg2);
}

export function DeleteAIToolSession(arg1, arg2) {
  return window['go']['main']['App']['DeleteAIToolSession'](arg1, arg2);
}

export function DetectAIToolDefaults() {
  return window['go']['main']['App']['DetectAIToolDefaults']();
}

export function EnsureAgent() {
  return window['go']['main']['App']['EnsureAgent']();
}

export function GetAIToolSessionDetail(arg1, arg2) {
  return window['go']['main']['App']['GetAIToolSessionDetail'](arg1, arg2);
}

export function GetSessionDetail(arg1) {
  return window['go']['main']['App']['GetSessionDetail'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ListAIToolSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListAIToolSessions'](arg1, arg2, arg3);
}

export function ListSessions(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2, arg3);
}

export function Login(arg1) {
  return window['go']['main']['App']['Login'](arg1);
}

export function Logout() {
  return window['go']['main']['App']['Logout']();
}

export function Offline() {
  return window['go']['main']['App']['Offline']();
}

export function ReplySession(arg1, arg2) {
  return window['go']['main']['App']['ReplySession'](arg1, arg2);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
